### ISSUE TITLE
Can't send metrics to Dynatrace over otlp from Lambda

### ISSUE THREAD

**Issue by alexandr2110pro** [aws-observability/aws-otel-lambda#1071]
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: bug
assignees: ''

---

**Describe the bug**
Can not use recommended configuration for Dynatrace with lambda

**Steps to reproduce**

Create an account in dynatrace, create the API KEY with the required scopes

Create a nodejs (not sure about other platforms) lambda function auto-instrumented with ADOT layers
  - `arn:aws:lambda:us-east-1:184161586896:layer:opentelemetry-nodejs-0_11_0:1`
  - `arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-nodejs-arm64-ver-1-30-1:1`

Use the collector.yaml [configuration recommended for dynatrace in official ADOT docs ](https://aws-otel.github.io/docs/components/otlp-exporter#dynatrace):
```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  otlphttp:
    endpoint: "https://{your-environment-id}.live.dynatrace.com/api/v2/otlp"
    headers:
      Authorization: "Api-Token <API_TOKEN>"
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlphttp]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [otlphttp]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [otlphttp]
```

Test the function, see the error logs on cloudwatch
```
{
    "level": "error",
    "ts": 1739268724.6115236,
    "caller": "internal/base_exporter.go:139",
    "msg": "Exporting failed. Rejecting data. Try enabling sending_queue to survive temporary failures.",
    "kind": "exporter",
    "data_type": "metrics",
    "name": "otlphttp",
    "error": "not retryable error: Permanent error: rpc error: code = InvalidArgument desc = error exporting items, request to https://trn07088.live.dynatrace.com/api/v2/otlp/v1/metrics responded with HTTP Status Code 400, Message=All metric data points were rejected. The following issues were encountered while ingesting OTLP metrics:\nErrors:\nUnsupported metric: 'http.client.duration' - Reason: UNSUPPORTED_METRIC_TYPE_CUMULATIVE_HISTOGRAM\n, Details=[]",
    "rejected_items": 3,
    "stacktrace": "go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*BaseExporter).Send\n\tgo.opentelemetry.io/collector/exporter@v0.115.0/exporterhelper/internal/base_exporter.go:139\ngo.opentelemetry.io/collector/exporter/exporterhelper.NewMetricsRequest.func1\n\tgo.opentelemetry.io/collector/exporter@v0.115.0/exporterhelper/metrics.go:135\ngo.opentelemetry.io/collector/consumer.ConsumeMetricsFunc.ConsumeMetrics\n\tgo.opentelemetry.io/collector/consumer@v1.22.0/metrics.go:26\ngo.opentelemetry.io/collector/consumer.ConsumeMetricsFunc.ConsumeMetrics\n\tgo.opentelemetry.io/collector/consumer@v1.22.0/metrics.go:26\ngo.opentelemetry.io/collector/receiver/otlpreceiver/internal/metrics.(*Receiver).Export\n\tgo.opentelemetry.io/collector/receiver/otlpreceiver@v0.115.0/internal/metrics/otlp.go:41\ngo.opentelemetry.io/collector/receiver/otlpreceiver.handleMetrics\n\tgo.opentelemetry.io/collector/receiver/otlpreceiver@v0.115.0/otlphttp.go:76\ngo.opentelemetry.io/collector/receiver/otlpreceiver.(*otlpReceiver).startHTTPServer.func2\n\tgo.opentelemetry.io/collector/receiver/otlpreceiver@v0.115.0/otlp.go:146\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2220\nnet/http.(*ServeMux).ServeHTTP\n\tnet/http/server.go:2747\ngo.opentelemetry.io/collector/config/confighttp.(*decompressor).ServeHTTP\n\tgo.opentelemetry.io/collector/config/confighttp@v0.115.0/compression.go:175\ngo.opentelemetry.io/collector/config/confighttp.(*ServerConfig).ToServer.maxRequestBodySizeInterceptor.func2\n\tgo.opentelemetry.io/collector/config/confighttp@v0.115.0/confighttp.go:555\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2220\ngo.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP\n\tgo.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.56.0/handler.go:171\ngo.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1\n\tgo.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.56.0/handler.go:65\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2220\ngo.opentelemetry.io/collector/config/confighttp.(*clientInfoHandler).ServeHTTP\n\tgo.opentelemetry.io/collector/config/confighttp@v0.115.0/clientinfohandler.go:26\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:3210\nnet/http.(*conn).serve\n\tnet/http/server.go:2092"
}
```

**What did you expect to see?**
Docs describing an actual way to send logs, traces and metrics to Dynatrace.

**What did you see instead?**
An error

**What version of collector/language SDK version did you use?**
  - `arn:aws:lambda:us-east-1:184161586896:layer:opentelemetry-nodejs-0_11_0:1`
  - `arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-nodejs-arm64-ver-1-30-1:1`

**What language layer did you use?**
Node 

**Additional context**
no
