### ISSUE TITLE
Lambda traces not being sent to data-prepper

### ISSUE THREAD

**Issue by imanol-uribe** [aws-observability/aws-otel-lambda#125]
Hello,
I am trying to send trace data from a lambda to my data-prepper server which I have running on an EC2 instance.
Currently I can only see the traces on AWS X-ray. 

My config.template.yaml file: 
```
receivers:
  otlp:
    protocols:
      grpc:
exporters:
  logging:
    loglevel: debug
  otlp/data-prepper:
    endpoint: ec2-user@ec2-34-219-158-153.us-west-2.compute.amazonaws.com:21890
    insecure: true
processors:
  batch:
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp/data-prepper]
```
I am using the following environment variables:
```
OPENTELEMETRY_COLLECTOR_CONFIG_FILE: /var/task/collector.yaml/collector.template.yaml
AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-proxy-handler
```
I followed [this](https://aws-otel.github.io/docs/getting-started/lambda/lambda-java) guide, and used the lambda layer `arn:aws:lambda:\us-west-2:901920570463:layer:aws-otel-java-wrapper-ver-1-2-0:2`. I also used [this](https://aws-otel.github.io/docs/getting-started/lambda) guide to instead of sending the trace data to X-ray to send to data-prepper. 

Is there something my set-up is missing?

I believe the issue may be that the the lambda layer and thus the config file (which exists in the correct directory after deploying lambda) is never being used, as the open-telemetry is never outputting any logs, (even though as shown in the config file it should be posting debug logs and exporting to data-prepper). 

I would appreciate any suggestions or help with the matter, and please let me know if you have any questions/ need any more information for me.
