### ISSUE TITLE
Overriding Collector Config With Collector Layer Doesn't Appear To Work

### ISSUE THREAD

**Issue by kolanos** [aws-observability/aws-otel-lambda#204]
I am attempting to use the layer `arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-collector-ver-0-39-0:1` with aGo function.

My Go function is identical to the sample app.

But the collector doesn't appear to be letting me override the config to use my own exporter.

I am setting `OPENTELEMETRY_COLLECTOR_CONFIG_FILE` to `/var/task/collector.yaml`.

With the contents:

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlp:
    endpoint: ${OPENTELEMETRY_ENDPOINT}
    headers:
      api-key: ${API_KEY}

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      exporters: [otlp]
```

But no telemetry is being exported to this endpoint. When I enable logging, I don't see this exporter getting loaded.

I am, however, still seeing traces in X-Ray. Which makes me think the collector is not using this config at all?

I have tested the Python layer with a Python function and the above worked fine. Not sure what the problem is with this collector layer. I know there was a bug with expanding environment variables in the collector config, could that be related?
