### ISSUE TITLE
AWS Python Lambda Layer 1.9.1 default export protocol

### ISSUE THREAD

**Issue by ericksoen** [aws-observability/aws-otel-lambda#223]
**Works as expected**

Layer version: arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-python38-ver-1-7-1:1

_config.yaml_
```yaml
receivers:
  otlp:
    protocols:
      grpc:
exporters:
  logging:
    logLevel: debug
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging]
```

**Does not work**

Layer version: arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-python38-amd64-ver-1-9-1:1

_config.yaml_
```yaml
receivers:
  otlp:
    protocols:
      grpc:
exporters:
  logging:
    logLevel: debug
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging]
```

```txt
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4318): Max retries exceeded with url: /v1/traces
```

Port `4318` is the default OTLP port for HTTP traffic so adding the `http` key to the `otlp` receiver protocols resolves the issue. I'm still new to this space, so I'm trying to understand which of the potential layer contents introduces the isue:

* OpenTelemetry Python v1.9.1
* AWS Python Extension v2.0.1
* ADOT Collector for Lambda v0.16.0
