### ISSUE TITLE
Spans being dropped

### ISSUE THREAD

**Issue by chris-armstrong** [aws-observability/aws-otel-lambda#229]
Some of my spans are being dropped by the lambda nodejs layer. I'm experiencing errors like the following in my CloudWatch logs:

```
2022-03-02T01:07:36.673Z	error	exporterhelper/queued_retry_inmemory.go:93	Exporting failed. No more retries left. Dropping data.	
{
    "kind": "exporter",
    "name": "otlp",
    "error": "max elapsed time expired rpc error: code = DeadlineExceeded desc = context deadline exceeded",
    "dropped_items": 3
}
```

I've tried tweaking my collector configuration to extend timeouts and the like, but I get the impression these errors are caused by the Lambda container going to sleep while spans are being sent, as these errors appear either at the start of the next request to the same container, or when it is shutting down.

My collector configuration is as follows:
```yaml
receivers:
  otlp:
    protocols:
      http:

exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: api.honeycomb.io:443
    headers:
      "x-honeycomb-team": "${HONEYCOMB_API_KEY}"
      "x-honeycomb-dataset": "${NORMALISED_ENVIRONMENT_NAME}"
    retry_on_failure:
      max_elapsed_time: 900 
      max_interval: 30
      initial_interval: 2
    
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
```

I'm using `arn:aws:lambda:ap-southeast-2:901920570463:layer:aws-otel-nodejs-amd64-ver-1-0-1:1`.

Is there something wrong with my configuration that stops it from sending the spans before it goes to sleep? I am not setting `context.callbackWaitsForEmptyEventLoop` to `false` (I presume it defaults to `true`)
