### ISSUE TITLE
Cloudwatch log noise when loglevel set to `error`

### ISSUE THREAD

**Issue by M3gar00** [aws-observability/aws-otel-lambda#237]
Expected Behavior: That setting loglevel to `error` would suppress ADOT logs in cloudwatch.

Actual Behavior: Setting loglevel seems to have no impact on cloudwatch logs.

We regularly use Cloudwatch Logs to debug our lambdas, but the ADOT layer is creating a lot of log noise. As you can see from the sample log below, the layer produces a lot of noise. I assumed that, since the logs are labeled as, 'info', that setting the config loglevel to `error`, that it would suppress these logs. That was not the case.

```
2022-03-15T10:50:19.273-04:00 | 2022/03/15 14:50:19 Using config file at path /var/task/file_path/config.yaml
-- | --
  | 2022-03-15T10:50:19.274-04:00 | 2022-03-15T14:50:19.273Z info builder/exporters_builder.go:255 Exporter was built. {"kind": "exporter", "name": "awsxray"}
  | 2022-03-15T10:50:19.275-04:00 | 2022-03-15T14:50:19.274Z info builder/exporters_builder.go:255 Exporter was built. {"kind": "exporter", "name": "logging"}
  | 2022-03-15T10:50:19.275-04:00 | 2022-03-15T14:50:19.275Z info builder/pipelines_builder.go:223 Pipeline was built. {"name": "pipeline", "name": "traces"}
  | 2022-03-15T10:50:19.275-04:00 | 2022-03-15T14:50:19.275Z info builder/receivers_builder.go:226 Receiver was built. {"kind": "receiver", "name": "otlp", "datatype": "traces"}
  | 2022-03-15T10:50:19.275-04:00 | 2022-03-15T14:50:19.275Z info service/service.go:82 Starting extensions...
  | 2022-03-15T10:50:19.275-04:00 | 2022-03-15T14:50:19.275Z info service/service.go:87 Starting exporters...
  | 2022-03-15T10:50:19.275-04:00 | 2022-03-15T14:50:19.275Z info builder/exporters_builder.go:40 Exporter is starting... {"kind": "exporter", "name": "awsxray"}
  | 2022-03-15T10:50:19.275-04:00 | 2022-03-15T14:50:19.275Z info builder/exporters_builder.go:48 Exporter started. {"kind": "exporter", "name": "awsxray"}
  | 2022-03-15T10:50:19.275-04:00 | 2022-03-15T14:50:19.275Z info builder/exporters_builder.go:40 Exporter is starting... {"kind": "exporter", "name": "logging"}
  | 2022-03-15T10:50:19.275-04:00 | 2022-03-15T14:50:19.275Z info builder/exporters_builder.go:48 Exporter started. {"kind": "exporter", "name": "logging"}
  | 2022-03-15T10:50:19.275-04:00 | 2022-03-15T14:50:19.275Z info service/service.go:92 Starting processors...
  | 2022-03-15T10:50:19.275-04:00 | 2022-03-15T14:50:19.275Z info builder/pipelines_builder.go:54 Pipeline is starting... {"name": "pipeline", "name": "traces"}
  | 2022-03-15T10:50:19.275-04:00 | 2022-03-15T14:50:19.275Z info builder/pipelines_builder.go:65 Pipeline is started. {"name": "pipeline", "name": "traces"}
  | 2022-03-15T10:50:19.275-04:00 | 2022-03-15T14:50:19.275Z info service/service.go:97 Starting receivers...
  | 2022-03-15T10:50:19.275-04:00 | 2022-03-15T14:50:19.275Z info builder/receivers_builder.go:68 Receiver is starting... {"kind": "receiver", "name": "otlp"}
  | 2022-03-15T10:50:19.276-04:00 | 2022-03-15T14:50:19.275Z info otlpreceiver/otlp.go:69 Starting GRPC server on endpoint 0.0.0.0:4317 {"kind": "receiver
```
My `config.yaml` is as follows:
```
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: error
  awsxray:

#enables output for traces to xray
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [awsxray]
```

**Comment by Aneurysm9** [comment]
That setting affects the level of the `logging` exporter.  To control the log level for the collector service you would need to set the `service.telemetry.logs.level` attribute:

```yaml
service:
  telemetry:
    logs:
      level: error
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [awsxray]
```
