### ISSUE TITLE
Failed to start the extension: failed to get config: cannot unmarshal the configuration: unknown processors type "resource" for "resource" (valid values: [])

### ISSUE THREAD

**Issue by EddieEldridge** [aws-observability/aws-otel-lambda#265]
**Is your feature request related to a problem? Please describe.**
I can't use the resource processor. When the Collector starts, I get the following error `Failed to start the extension: failed to get config: cannot unmarshal the configuration: unknown processors type "resource" for "resource" (valid values: [])`

**Describe the solution you'd like**
I would like the resource processor to work.

**Additional context**
config.yaml
```yaml
# ==================================
#             RECEIVERS
# ==================================
receivers:
  otlp:
    protocols:
      http:
# ==================================
#             EXPORTERS
# ==================================
exporters:
  logging:
    loglevel: debug
  otlp/new_relic_metric:
    endpoint: ${NEW_RELIC_OPENTELEMETRY_METRIC_ENDPOINT}
    headers:
      api-key:  ${NEW_RELIC_LICENSE_KEY}
  otlp/new_relic_trace:
    endpoint: ${NEW_RELIC_OPENTELEMETRY_TRACE_ENDPOINT}
    headers:
      api-key:  ${NEW_RELIC_LICENSE_KEY}
# ==================================
#             PROCESSORS
# ==================================
processors:
  resource:
    attributes:
    - key: service.name
      value: ${ROLE}-${ENVIRONMENT}
      action: upsert
    - key: tags.service.region
      value: ${REGION}
      action: upsert
    - key: tags.fips.enabled
      value: ${FIPS_ENABLED}
      action: upsert
    - key: tags.aws.account.id
      value: ${ACCOUNT_ID}
      action: upsert
    - key: tags.nr.account.id
      value: ${NEW_RELIC_ACCOUNT_ID}
      action: upsert
# ==================================
#             SERVICE
# ==================================
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp/new_relic_trace]
      processors: [resource]
    metrics:
      receivers: [otlp]
      exporters: [logging, otlp/new_relic_metric]
      processors: [resource]
 ```
