### ISSUE TITLE
Missing root spans in non-xray provider

### ISSUE THREAD

**Issue by Compulsed** [aws-observability/aws-otel-lambda#361]
It is unclear whether this layer can / should be used with other OTEL destinations outside of XRay. 

**Describe the bug**
When exporting traces to Honeycomb, it is missing the root trace (screenshot) -- Honeycomb recommends using this layer https://docs.honeycomb.io/getting-data-in/integrations/aws/aws-lambda/) 

**Steps to reproduce**
- Utilize the AWS layer
- Specify the export as honeycomb on the configuration.yaml (via the headers / end-point)

**What did you expect to see?**
A root trace is present

**What did you see instead?**
Missing root trace (sceenshot)

**Environment**

`OTEL_EXPORTER_OTLP_HEADERS` is set in the environment.

```
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlp/traces:
    endpoint: api.honeycomb.io:443

  logging:
    loglevel: debug

service:
  extensions: []
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp/traces]
```

**Additional context**

1/ I suspect this issue is related to the fact that the root span comes from the lambda data plane, and is sent to XRay and not the 3rd party trace visualization tool. I understand the new telemetry API might solve this problem.
2/ If the intent is be able to use this extension for other otel providers, it seems strange that you need to set `Tracing.ACTIVE` to true for spans to be sent

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/1109278/203465882-2ef1cbd2-92b5-4401-98eb-49e21a7c444e.png">
