### ISSUE TITLE
How to enable debugging of the collector in the layer

### ISSUE THREAD

**Issue by MarkFischer** [aws-observability/aws-otel-lambda#430]
I'm having a problem where it seems that traces that are 'too big' don't send at all. I'm trying to see if there's any additional information I can get out of the collector, since no errors are generated that I can see. According to some other threads I've found, you can enable collector debugging with `loggingLevel` in `extracfg.txt`, but I can't figure out how to do that with the lambda layer, unless I need to build my own?

> [sethAmazon](https://github.com/sethAmazon) commented [on Jun 28, 2021](https://github.com/aws-observability/aws-otel-lambda/issues/new#issuecomment-869701111)
> From the docs
> enable debugging log
> add a key value pair into /opt/aws/aws-otel-collector/etc/extracfg.txt and restart collector
> 
> echo "loggingLevel=DEBUG" | sudo tee -a /opt/aws/aws-otel-collector/etc/extracfg.txt
> sudo /opt/aws/aws-otel-collector/bin/aws-otel-collector-ctl -a stop
> sudo /opt/aws/aws-otel-collector/bin/aws-otel-collector-ctl -a start

https://github.com/aws-observability/aws-otel-collector/issues/547#issuecomment-869701111

My underlying problem is that it seems if I send either too many spans with my trace, or a small number of spans with even moderately sized attributes (just a few hundred characters), none of my spans are sent to Honeycomb. I must be hitting some limit, but there's no errors printed out to the lambda logs.

My collector.yaml file looks like this currently. The spans I'm trying to send do output to the lambda logs in a debug message, but there's no errors displayed that look anything like a size limit, or a send failure.

```
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlp:
    endpoint: api.honeycomb.io:443
    headers:
      "x-honeycomb-team": ${HONEYCOMB_KEY}
  logging:
    loglevel: debug

service:
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp, logging]
```
