### ISSUE TITLE
prometheus push exporter does not work for lambda collector

### ISSUE THREAD

**Issue by sasha-wing** [aws-observability/aws-otel-lambda#439]
**Describe the bug**
Prometheus metrics push exporter does not work.
And seems that event logging metrics exporter does not work

**Steps to reproduce**
I have used this configuration for my aws lambda
```
extensions:
  sigv4auth: 
    service: "aps"
    region: "us-east-1"
    assume_role:
        arn: {{ PrometheusIngestRoleArn }}
        sts_region: "us-east-1"
receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  logging:
    loglevel: debug
  awsxray:
  prometheusremotewrite:
    endpoint: "{{ PrometheusRemoteWriteEndpoint }}"
    auth:
      authenticator: sigv4auth
service:
  pipelines:
    traces:
      exporters: [awsxray]
    metrics:
      exporters: [prometheusremotewrite, logging]

  extensions: [sigv4auth]
```

**What did you expect to see?**
metrics and traces written to the aws lambda log group in cloudwatch and metrics written to my prometheus

**What did you see instead?**
Nothing

**Environment**
I have configured a role which has all permissions needed to push metrics to my APM,
Gave my lambda all needed permissions to assume this role

**Additional context**
No documentation practically exists for it

**Comment by vasireddy99** [comment]
Hello, thanks for sharing the details. By looking at the config looks like receivers are missing under  `pipelines:`. Please consider the below snippet as the reference. Also please look at [config](https://github.com/aws-observability/aws-otel-lambda/blob/main/adot/collector/config.yaml). Add more detail about the Error, Lambda Layer ARN if the issue still persists.

```
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [awsxray]
    metrics:
      receivers: [otlp]
      exporters: [prometheusremotewrite, logging]

  extensions: [sigv4auth]
```
