### ISSUE TITLE
Nodejs lambda works just with x-ray export

### ISSUE THREAD

**Issue by Amenocy** [aws-observability/aws-otel-lambda#579]
Hi, 

nodejs lambda + layer + otlp receiver and exporter (to data-prepper) via gRPC is not working, and why do we have to send traces to x-ray?  you cannot disable x-ray export anyway.

to reproduce you can use this config 

```
receivers:
  otlp:
    protocols:
      http:
        endpoint: localhost:4318
exporters:
  otlp:
    endpoint: data-prepper.*.net:21890

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]

    metrics:
      receivers: [otlp]
      exporters: [otlp]

```
data-prepper is behind aws-ALB and lambda is inside the same VPC.
