### ISSUE TITLE
Unable to access Lambda layer for Python with x86_64 architecture

### ISSUE THREAD

**Issue by gotgenes** [aws-observability/aws-otel-lambda#796]
**Describe the bug**

I am trying to follow the instructions for using [the Lambda Support layer with Python](https://aws-otel.github.io/docs/getting-started/lambda/lambda-python), applying it to [the `sam-hello-world` project described in the SAM tutorial](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-getting-started-hello-world.html#serverless-getting-started-hello-world-init). The layer does not appear to be accessible for x86_64 architecture.

**Steps to reproduce**

Follow [the SAM tutorial](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-getting-started-hello-world.html). I changed `python3.9` to `python3.10`.

Observe that the application deploys successfully.

Next, add in [the Lambda Layer](https://aws-otel.github.io/docs/getting-started/lambda/lambda-python):

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Layers:
        - !Sub 'arn:aws:lambda:${AWS::Region}:901920570463:layer:aws-otel-python-x86_64-ver-1-20-0:3'
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
```

Run `sam build` and then `sam deploy` and you should see an error with the following text:

```
[…] is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:us-east-2:901920570463:layer:aws-otel-python-x86_64-ver-1-20-0:3 because no resource-based policy allows the lambda:GetLayerVersion action
```

If instead I change the architectures from `x86_64` to `arm64`, run `sam build` again, then `sam deploy` will succeed. So this seems to be specific to the `x86_64` architecture.

**What did you expect to see?**

I expected `sam deploy` to complete successfully with output like below:

```
CloudFormation events from stack operations (refresh every 5.0 seconds)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
ResourceStatus                                       ResourceType                                         LogicalResourceId                                    ResourceStatusReason
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE_IN_PROGRESS                                   AWS::CloudFormation::Stack                           sam-hello-world                                      User Initiated
CREATE_IN_PROGRESS                                   AWS::IAM::Role                                       HelloWorldFunctionRole                               -
CREATE_IN_PROGRESS                                   AWS::IAM::Role                                       HelloWorldFunctionRole                               Resource creation Initiated
CREATE_COMPLETE                                      AWS::IAM::Role                                       HelloWorldFunctionRole                               -
CREATE_IN_PROGRESS                                   AWS::Lambda::Function                                HelloWorldFunction                                   -
CREATE_IN_PROGRESS                                   AWS::Lambda::Function                                HelloWorldFunction                                   Resource creation Initiated
CREATE_COMPLETE                                      AWS::Lambda::Function                                HelloWorldFunction                                   -
CREATE_IN_PROGRESS                                   AWS::ApiGateway::RestApi                             ServerlessRestApi                                    -
CREATE_IN_PROGRESS                                   AWS::ApiGateway::RestApi                             ServerlessRestApi                                    Resource creation Initiated
CREATE_COMPLETE                                      AWS::ApiGateway::RestApi                             ServerlessRestApi                                    -
CREATE_IN_PROGRESS                                   AWS::ApiGateway::Deployment                          ServerlessRestApiDeployment47fc2d5f9d                -
CREATE_IN_PROGRESS                                   AWS::Lambda::Permission                              HelloWorldFunctionHelloWorldPermissionProd           -
CREATE_IN_PROGRESS                                   AWS::Lambda::Permission                              HelloWorldFunctionHelloWorldPermissionProd           Resource creation Initiated
CREATE_COMPLETE                                      AWS::Lambda::Permission                              HelloWorldFunctionHelloWorldPermissionProd           -
CREATE_IN_PROGRESS                                   AWS::ApiGateway::Deployment                          ServerlessRestApiDeployment47fc2d5f9d                Resource creation Initiated
CREATE_COMPLETE                                      AWS::ApiGateway::Deployment                          ServerlessRestApiDeployment47fc2d5f9d                -
CREATE_IN_PROGRESS                                   AWS::ApiGateway::Stage                               ServerlessRestApiProdStage                           -
CREATE_IN_PROGRESS                                   AWS::ApiGateway::Stage                               ServerlessRestApiProdStage                           Resource creation Initiated
CREATE_COMPLETE                                      AWS::ApiGateway::Stage                               ServerlessRestApiProdStage                           -
CREATE_COMPLETE                                      AWS::CloudFormation::Stack                           sam-hello-world                                      -
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**What did you see instead?**

```
CloudFormation events from stack operations (refresh every 5.0 seconds)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
ResourceStatus                                       ResourceType                                         LogicalResourceId                                    ResourceStatusReason
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE_IN_PROGRESS                                   AWS::CloudFormation::Stack                           sam-hello-world                                      User Initiated
CREATE_IN_PROGRESS                                   AWS::IAM::Role                                       HelloWorldFunctionRole                               -
CREATE_IN_PROGRESS                                   AWS::IAM::Role                                       HelloWorldFunctionRole                               Resource creation Initiated
CREATE_COMPLETE                                      AWS::IAM::Role                                       HelloWorldFunctionRole                               -
CREATE_IN_PROGRESS                                   AWS::Lambda::Function                                HelloWorldFunction                                   -
CREATE_IN_PROGRESS                                   AWS::Lambda::Function                                HelloWorldFunction                                   Resource creation Initiated
CREATE_FAILED                                        AWS::Lambda::Function                                HelloWorldFunction                                   Resource handler returned message: "User:
                                                                                                                                                               arn:aws:sts::109411978368:assumed-role/AWSReserved
                                                                                                                                                               SSO_AdministratorAccess_14ea24479451150a/clasher
                                                                                                                                                               is not authorized to perform:
                                                                                                                                                               lambda:GetLayerVersion on resource:
                                                                                                                                                               arn:aws:lambda:us-east-2:901920570463:layer:aws-
                                                                                                                                                               otel-python-x86_64-ver-1-20-0:3 because no
                                                                                                                                                               resource-based policy allows the
                                                                                                                                                               lambda:GetLayerVersion action (Service: Lambda,
                                                                                                                                                               Status Code: 403, Request ID:
                                                                                                                                                               43f87ca0-7208-40c9-b06d-55043f3026ad)"
                                                                                                                                                               (RequestToken:
                                                                                                                                                               83c0cd8b-bb8d-8b27-2c2f-b470d56994be,
                                                                                                                                                               HandlerErrorCode: AccessDenied)
ROLLBACK_IN_PROGRESS                                 AWS::CloudFormation::Stack                           sam-hello-world                                      The following resource(s) failed to create:
                                                                                                                                                               [HelloWorldFunction]. Rollback requested by user.
DELETE_IN_PROGRESS                                   AWS::Lambda::Function                                HelloWorldFunction                                   -
DELETE_COMPLETE                                      AWS::Lambda::Function                                HelloWorldFunction                                   -
DELETE_IN_PROGRESS                                   AWS::IAM::Role                                       HelloWorldFunctionRole                               -
DELETE_COMPLETE                                      AWS::IAM::Role                                       HelloWorldFunctionRole                               -
ROLLBACK_COMPLETE                                    AWS::CloudFormation::Stack                           sam-hello-world                                      -
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Error: Failed to create/update the stack: sam-hello-world, Waiter StackCreateComplete failed: Waiter encountered a terminal failure state: For expression "Stacks[].StackStatus" we matched expected path: "ROLLBACK_COMPLETE" at least once
```

**What version of collector/language SDK version did you use?**
Version: `arn:aws:lambda:us-east-2:901920570463:layer:aws-otel-python-x86_64-ver-1-20-0:3`

**What language layer did you use?**
Config: `Python`
