### ISSUE TITLE
Does not work with custom metrics

### ISSUE THREAD

**Issue by stevemao** [aws-observability/aws-otel-lambda#847]
**Describe the bug**

Metrics is not exported.

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

Step 1. follow
https://aws-otel.github.io/docs/getting-started/lambda/lambda-js
All default config. metrics should be exported to log which should be visible on cloudwatch

Step 2.
Add 

```ts
import { metrics } from '@opentelemetry/api';

// Create a meter
export const meter = metrics.getMeter('your-metric-name');

// Define a counter metric
export const requestCounter = meter.createCounter('my-requests', {
  description: 'Counts number of requests processed',
});

requestCounter.add(1, { functionName: context.functionName });
```

In my lambda

**What did you expect to see?**
A clear and concise description of what you expected to see.

metrics in log which should be in cloudwatch

**What did you see instead?**
A clear and concise description of what you saw instead.

no metrics. I can see traces in xray

**What version of collector/language SDK version did you use?**
Version: (e.g., `v0.58.0`, `v1.11.0`, etc)

latest

**What language layer did you use?**
Config: (e.g., `Java`, `Python`, etc)

Nodejs

**Additional context**

**Comment by stevemao** [comment]
Not stale

**Comment by stevemao** [comment]
Not stale

**Comment by stevemao** [comment]
Not stale

**Comment by stevemao** [comment]
Not stale

**Comment by mwood23** [comment]
Fwiw, I hit this today and got it figured out by supplying a custom `collector.yaml`. They don't default metrics collection to one so you have to supply a config.

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  awsxray: # traces → X-Ray
  awsemf: # metrics → CloudWatch (EMF)

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [awsxray]
    metrics:
      receivers: [otlp]
      exporters: [awsemf]

```

**Comment by solaris-marco** [comment]
Hey @mwood23. Are you using the config at scale like this?
I'm concerned about the default log stream name used by the emf exporter. Considering that a log stream should only be written to by one process I'd want to configure it to be unique by lambda execution environment. I figured this would make sense:

```
exporters:
  awsemf:
    retain_initial_value_of_delta_metric: true
    dimension_rollup_option: NoDimensionRollup
    log_group_name: /emf/${env:AWS_LAMBDA_FUNCTION_NAME}
    log_retention: 7
    log_stream_name: ${env:AWS_LAMBDA_LOG_STREAM_NAME}
    namespace: custom-metrics
    resource_to_telemetry_conversion:
      enabled: true
```

Seemingly the `AWS_LAMBDA_LOG_STREAM_NAME ` variable is not available at the point in time when the OTEL collector is started during function init. I'm wondering if anyone out there is already using OTEL metrics in AWS. Everything feels pretty rough and not really thought through to the end yet.
