### ISSUE TITLE
awsemf exporter won't create any log group, nor generating any metrics

### ISSUE THREAD

**Issue by stevemao** [aws-observability/aws-otel-lambda#849]
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: bug
assignees: ''

---

**Describe the bug**

I was able to patch the instrument and generate metrics with logging exporter. I can see the metrics in cloudwatch console. Now I change the exporter to awsemf but I do no see the new log group being created.

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

Change the default exporter to awsemf

**What did you expect to see?**
A clear and concise description of what you expected to see.

A new log group about metrics should be created, and emf formatted logs should be populated. Then the metrics should show it

**What did you see instead?**
A clear and concise description of what you saw instead.

No new log group is created

**What version of collector/language SDK version did you use?**
Version: (e.g., `v0.58.0`, `v1.11.0`, etc)

latest

**What language layer did you use?**
Config: (e.g., `Java`, `Python`, etc)

nodejs

**Additional context**

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "localhost:4317"
      http:
        endpoint: "localhost:4318"

exporters:
  logging:
  awsxray:
  awsemf:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [awsxray]
    metrics:
      receivers: [otlp]
      exporters: [awsemf]
  telemetry:
    metrics:
      address: localhost:8888
```
